panel_client_cert: |
  -----BEGIN CERTIFICATE-----
  MIIEnDCCAoQCAQAwDQYJKoZIhvcNAQENBQAwEzERMA8GA1UEAwwIR296YXJnYWgw
  IBcNMjYwMzEzMTAzNjI3WhgPMjEyNjAyMTcxMDM2MjdaMBMxETAPBgNVBAMMCEdv
  emFyZ2FoMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5kuIQQcWG3ct
  O9QX1Igw12HG0CjmOfFvfe2LrIIj+YojUuyYGmDXHff2rwKXvxl5wkVOwnCm4K5K
  j3iykdjxHlam+wxICHFKyIT409q+SuRjn61L1vDF4GsUOs10dslULlBZVqwsMrAu
  6WxeuQG0mzD/5NY7vpsIb1RdvS++O1oqid+rzQOqp0KuvUulbzBACnFuisCgrLjd
  lKbEqGlYw+3VX70bgb6meUakBqkphM0LvWaJprLJMeb7Mq7j6l/gfE1pY+EieuuB
  tt2EO5aSOD8BrxFpsepr6S7RPMQJSaMoMUWf2KoRfy6GpW5NPWfxRzJ/k7WsYgWB
  zjJvWQynoyV6992utAx6E5CY60t8SpwlDmX0HNOtVQdgbSWDF9AtY0o751gHkbzx
  klh36tH0IAagsy4wRMT/kxN0YOCWd2BPVysw8wYmch4NmqQY/8i9XUf4QVUmYdda
  EegALTOT+rYToWSEhs9i9AKrN4bF5aSX8vvZtuJSf8MVCbNNsDMxOoyZIBn74Rdq
  hXZFRQ5wpjwuIgL5zqrkpC5548NAWY62gOOUuktpMByRibnLoqRqDnAEWOUEHJvl
  NoSHiyW47ESUyh2ypmUk1DfTN1Wre6UE4W8K8SFmGpUkLNHF5GB7YmN//2zy3iWb
  YdmBQo8zU6WDqmIOVtdZjYA1mAG5J+MCAwEAATANBgkqhkiG9w0BAQ0FAAOCAgEA
  Tys8FR9SXpDoqmyPty6NagOjbW8ZCjMqIIVJiJJoxw36lrHlgGIW9DGQV/6pJcIn
  EZ5iu5QWhs+H7DcsX+uY2q5xuAbBLkarYgliUFmIAWnw1DWRxlX5PB//bU0SE01w
  R/XgGzUhtMeSxWZMf2eQXF7hdiPCRK7cNuQrNSIdwdQx8rL7SNQXBM6ebhvJXq42
  zTS3K7fAmilYlXDs9zMLp4qmONZtWYDlbAeAM7I5HsJiIY0KCaK+mhYYik01u5ID
  sKjhYQ6KQ85Tfi4E5/vg2PZY4zExRZNsevz9RBHC+b11TZKocb1hiW80efjx1QVb
  zZnfrb4Wvsg1Mvw01wT1/8Rm3nH3Ep6kP5cWAd/aSiJ41uS3Lk5vvQWXeVxph9pZ
  AHiUWENkbT3CBDNUekqZBTJIEIhe60vldCANbkUjt3LxZHwLEiQNstP6QbmbWKTL
  fVlHvXLo3+BHngjXeGGFdjbOpF+XVY9LLc+alfobQpCY3JH6EKtJwEnorY2Fu6TU
  QNbcCfxCNv7or0qZ/SoVYcFCzExjNQp6cLynFkmBFU7cI63tOt/KIuVuTcOq1JiO
  iYNGQLf8adIUUpak1u5UIumjVU4PKn2MfxwMN4D+xHaZTulx3MdMMpKcYGjO5TAQ
  SsdlArLZnKrDeoAkxU9WULsA/ft3hOou8GNmDjlRnrM=
  -----END CERTIFICATE-----
