[pasarguard]
dev-panel ansible_host=smart-sausage.de ansible_user=root
prod-panel ansible_host=domoi-panel.ru ansible_user=root

[pasarguard_nodes]
node-nsk-1 ansible_host=188.119.64.160 ansible_user=root
node-msk-1 ansible_host=62.109.26.25 ansible_user=root
node-msk-2 ansible_host=155.212.170.183 ansible_user=root
node-piter-1 ansible_host=217.114.9.60 ansible_user=root

[pasarguard_nodes:vars]
caddy_stub_domain=sw.smart-sausage.de
caddy_stub_port=8443