[pasarguard_main]
main-panel ansible_host=smart-sausage.de ansible_user=root

[pasarguard_nodes]
node-nsk-1 ansible_host=188.119.64.160 ansible_user=root
node-msk-1 ansible_host=62.109.26.25 ansible_user=root