[pasarguard]
dev-panel ansible_host=smart-sausage.de ansible_user=root
prod-panel ansible_host=domoi-panel.ru ansible_user=root

[pasarguard_nodes]
node-msk-2 ansible_host=155.212.170.183 ansible_user=root caddy_stub_domain=msk.smart-sausage.de caddy_stub_port=8443
node-sweden ansible_host=89.125.76.65 ansible_user=root caddy_stub_domain=sw.smart-sausage.de caddy_stub_port=8443
node-italy ansible_host=185.198.235.140 ansible_user=root caddy_stub_domain=it.smart-sausage.de caddy_stub_port=8443